#!/usr/bin/env python3
import os
import sys

if len(sys.argv) != 2:
    print("Usage: ./scripts/kattis_submit problemname")
    exit(0)

def is_part_of_program(name):
    X = ['.py', '.cpp', '.hpp', '.h', '.c']
    return any(name.endswith(fileextension) for fileextension in X)

problemname = sys.argv[1]
problem_path = os.path.join('kattis', problemname)
items = os.listdir(problem_path)
items = list(filter(is_part_of_program, items))
main = [x for x in items if x.startswith(problemname)]
if not main:
    print("Could not find main file!")
    exit(0)
main = main[0]

extra = ''
if main.endswith('.py'):
    # Kattis defaults to python2 but we look at the first line to
    # determine if it is python3 or not. (e.g. shebang)
    with open(os.path.join('kattis', problemname, main), 'r') as f:
        firstline = f.readline().strip()
    if 'python3' in firstline:
        extra = '-l "python 3"'


others = [os.path.join('kattis', problemname, x) for x in items if x != main]
main = os.path.join('kattis', problemname, main)


os.system('python scripts/submit.py {} -f {} {}'.format(extra, main, ' '.join(others)))
